name: Trigger auto deployment for remote

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/remote-AutoDeployTrigger-d554ca0d-c657-4139-b9b3-03296a6c2c79.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.REMOTE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: anicoledeploy7aed7b.azurecr.io
          registryUsername: ${{ secrets.REMOTE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REMOTE_REGISTRY_PASSWORD }}
          containerAppName: remote
          resourceGroup: anicole-test5
          imageToBuild: anicoledeploy7aed7b.azurecr.io/remote:${{ github.sha }}
          
            

     

